NAME: 'QCR.CLIPOrgRN50x4.AE.ROCO.VQARAD.16batchsize.200epoch.withTFIDF.nondeterministic'
OUTPUT_DIR: './output/clipOrgRN50x4/CLEF2019Organ'
CPU_MODE: False
SEED: 88

DATASET:
  DATASET: "CLEF2019Organ"
  DATA_DIR: r'your_path'
  DATA_TYPE: 'jpg'

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 1
  N_EPOCH: 31
  NUM_WORKERS: 2
  RESUME: False
  INPUT_SNAPSHOT: ""
  OPTIMIZER:
    TYPE: 'ADAMX'
    BASE_LR: 1e-3
    MOMENTUM_CNN: 0.05
    EPS_CNN: 1e-5
  ACTIVATION: 'relu'
  DROPOUT: 0.5
  ATTENTION:
    MODE: 'BAN'
    GLIMPSE: 10
    USE_COUNTER: False
    NUM_STACKS: 2    ## For SAN
  QUESTION:
    RNN: 'GRU'
    LENGTH: 12
    TFIDF: False
    CAT: True
    HID_DIM: 1024   ## Dim of joint semantic features
  VISION:
    V_DIM: 704    ## Visual input dim : 640(CLIP RNx40) + 64
    AUTOENCODER: True
    AE_PATH: "pretrained_ae.pth"
    AE_ALPHA: 0.001
    MAML: False
    CLIP: True
    CLIP_ORG: True
    CLIP_VISION_ENCODER: "RN50x4"
    OTHER_MODEL: False


TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 1
  NUM_WORKERS: 4